ensure kustomize sees all.yaml

diff --git a/.github/workflows/helm-template.yaml b/.github/workflows/helm-template.yaml
--- a/.github/workflows/helm-template.yaml
+++ b/.github/workflows/helm-template.yaml
@@ -17,27 +17,20 @@ jobs:
         uses: actions/checkout@v2
         with:
           fetch-depth: 0  # Fetch all history for all branches and tags
+          ref: main
+      - run: |
+          git config user.name ""github-actions[bot]""
+          git config user.email "github-actions[bot]@users.noreply.github.com"
 
       - name: Set up Helm
         uses: azure/setup-helm@v4.2.0
         with:
           version: 'v3.14.4'
-
-      - name: Create and checkout new branch
+      
+      - name: Get Directories for Processing
         run: |
-          # Generate a unique branch name based on the date and time
-          new_branch="temp-branch-$(date +%Y%m%d-%H%M%S)"
-          git checkout -b $new_branch
-
-      - name: Find changed directories
-        id: find_changed_dirs
-        run: |
-          # Ensure we have the latest state of 'main'
-          git fetch origin main:main
-          # Compare current new branch with 'main'
-          changed_dirs=$(git diff --name-only $new_branch origin/main~1 | grep -oE 'core/[^/]+/overlays/[^/]+' | sort -u | tr '\n' ',')
-          echo "dirs=$changed_dirs" >> $GITHUB_ENV
-        shell: /usr/bin/bash -e {0}
+            dirs=$(find "$(pwd)" -type d -regex '.*/core/[^/]+/overlays/[^/]+' | tr '\n' ',')
+            echo "dirs=${dirs%,}" >> $GITHUB_ENV
 
       - name: Add Helm repositories dynamically
         run: |
@@ -81,35 +74,52 @@ jobs:
             echo "Checking directory: $dir"  # Debug output
             if [ -d "$dir" ]; then
               cd $dir
-              pwd  # Debug: print current directory after cd
-              ls -lah  # List contents to verify
+              cd ../../base
               # Check if Chart.yaml exists before proceeding
-              if [ -f ../../base/Chart.yaml ]; then
+              if [ -f Chart.yaml ]; then
+                cd $dir
                 BASE_NAMESPACE=$(cat ../../base/kustomization.yaml | yq e '.namespace // "default"' -)
                 NAMESPACE=$(cat kustomization.yaml | yq e ".namespace // \"$BASE_NAMESPACE\"" -)
                 helm dependency build ../../base
                 touch ../../base/values.yaml
                 touch values.yaml
+                echo "Templating Helm chart in $dir"
                 helm template \
                   --release-name ${NAMESPACE} \
                   ../../base \
                   -f ../../base/values.yaml \
-                  -f values.yaml > all.yaml
-                ls -lah  # List contents to verify
+                  -f values.yaml > helm-all.yaml
               else
                 echo "Chart.yaml does not exist in $dir"
+                cd $dir
+
               fi
+              cd $dir
+              echo "running kustomize build . > all.yaml"
+              kustomize build . > all.yaml
+              git add all.yaml
+              echo $(head -n 10 all.yaml)
             else
               echo "$dir does not exist."
             fi
             cd $GITHUB_WORKSPACE  # Return to the initial directory
+            echo "Present Working Dir after build: $(pwd)"
           done
-
-
       - name: Commit changes to infra branch
-        uses: stefanzweifel/git-auto-commit-action@v5
-        with:
-            commit_message: "helm template $(date +%Y-%m-%d)"
-            commit_user_name: "github-actions[bot]"
-            commit_user_email: "github-actions[bot]@users.noreply.github.com"
-            branch: infra
+        run: |
+          git fetch origin infra:infra || true  # Fetch the infra branch if it exists, don't fail if it doesn't
+          git stash
+          if git show-ref --verify --quiet refs/heads/infra; then
+            git switch infra
+          else
+            git switch --create infra origin/infra || git switch --create infra
+          fi
+          git rm -rf . --quiet
+          git stash pop
+            git add **/all.yaml
+          if ! git diff --quiet --staged; then  # Ensure there are changes staged for commit
+            git commit -m "${{ github.event.head_commit.message }}"
+            git push --force --set-upstream origin infra
+          else
+            echo "No changes detected"
+          fi
